### ISSUE TITLE
Sonderzeichen

### ISSUE THREAD

**Issue by slydomkar** [Snej92/ProMa#15]
Können wir Sonderzeichen erlauben in der Projektmappe? Kann zb im Aufgabenfeld für die Versionen weder Klammern noch Umlaute noch Bindestriche nutzen.

Das schränkt schon ein.

**Comment by Snej92** [comment]
:, ; und ß kann ich ohne probleme hinzufügen. Für <> müsste ich nen sanitizer einbauen. Ich schau´s mir die tage mal an

**Comment by slydomkar** [comment]
interessant, ich kanns nämlich nich

**Comment by Snej92** [comment]
nein, ich mein damit das ich es zum regex hinzupacken kann damit es erlaubt ist :D Scheinbar kann ich <> auch einfach dazupacken, weil ich sowieso alles plain als text abspeicher und nichts als html intepretier sollte das auch keine probleme machen.
Kann das Regex auch erstmal komplett weg machen. 
Wenn ihr irgendwas wildes anstellt müsst ihr halt bescheid geben xD Nur bei den Kopfdaten muss ich ein recht striktes regex drin lassen, weil das sonst probleme bei anlegen von neuen stationen macht.
Ich sag bescheid wenn die neue version hochgeladen ist
